// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file ScrabbleSharp.proto (package ScrabbleSharp, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExpandDelta, ExpandRequest, LayoutRequest, LayoutResponse, SolveRequest, SolveResponse } from "./ScrabbleSharp_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ScrabbleSharp.ScrabbleSolver
 */
export const ScrabbleSolver = {
  typeName: "ScrabbleSharp.ScrabbleSolver",
  methods: {
    /**
     * @generated from rpc ScrabbleSharp.ScrabbleSolver.Solve
     */
    solve: {
      name: "Solve",
      I: SolveRequest,
      O: SolveResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ScrabbleSharp.ScrabbleSolver.GetLayout
     */
    getLayout: {
      name: "GetLayout",
      I: LayoutRequest,
      O: LayoutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ScrabbleSharp.ScrabbleSolver.Expand
     */
    expand: {
      name: "Expand",
      I: ExpandRequest,
      O: ExpandDelta,
      kind: MethodKind.Unary,
    },
  }
} as const;

